platform :ios, '7.0'

inhibit_all_warnings!

link_with 'BBQ', 'BBQTeacher', 'BBQMaster'

pod 'Qiniu'
pod 'QQ_XGPush'
pod 'SVProgressHUD'
pod 'Pingpp/Alipay'
pod 'Pingpp/Wx'
pod 'Bugly'
pod 'FMDB'
pod 'Masonry'
pod 'YYKit'
pod 'SSKeychain'
pod 'WMPageController'
pod 'CNPPopupController'
pod 'QBPopupMenu'
pod 'DateTools'
pod 'BlocksKit'
pod 'UITextField+Shake'
pod 'MZTimerLabel'
pod 'GCPlaceholderTextView'
pod 'KxMenu'
pod 'SSPullToRefresh', '1.2.4'
pod 'MYBlurIntroductionView'
pod 'WZLBadge'
pod 'IAPHelper'
pod 'LTNavigationBar'
pod 'TPKeyboardAvoiding'
pod 'iCarousel'
pod 'FDFullscreenPopGesture'
pod 'NYXImagesKit'
pod 'JDStatusBarNotification'
pod 'JazzHands', '2.0.8'
pod 'RegexKitLite-NoWarning'
pod 'FDStackView'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ReactiveCocoa'
pod 'MJExtension'
pod 'APParallaxHeader'
pod 'Harpy'
pod 'PopMenu', '2.4'
pod 'ObjcAssociatedObjectHelpers'
pod 'UMengSocial'

