
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 5
#define COCOAPODS_VERSION_PATCH_AFNetworking 4

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 4

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 4

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 4

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 4

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 4

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 4

// EGOTableViewPullRefreshAndLoadMore
#define COCOAPODS_POD_AVAILABLE_EGOTableViewPullRefreshAndLoadMore
#define COCOAPODS_VERSION_MAJOR_EGOTableViewPullRefreshAndLoadMore 1
#define COCOAPODS_VERSION_MINOR_EGOTableViewPullRefreshAndLoadMore 0
#define COCOAPODS_VERSION_PATCH_EGOTableViewPullRefreshAndLoadMore 4

// FDFullscreenPopGesture
#define COCOAPODS_POD_AVAILABLE_FDFullscreenPopGesture
#define COCOAPODS_VERSION_MAJOR_FDFullscreenPopGesture 1
#define COCOAPODS_VERSION_MINOR_FDFullscreenPopGesture 1
#define COCOAPODS_VERSION_PATCH_FDFullscreenPopGesture 0

// FMDB
#define COCOAPODS_POD_AVAILABLE_FMDB
#define COCOAPODS_VERSION_MAJOR_FMDB 2
#define COCOAPODS_VERSION_MINOR_FMDB 5
#define COCOAPODS_VERSION_PATCH_FMDB 0

// FMDB/common
#define COCOAPODS_POD_AVAILABLE_FMDB_common
#define COCOAPODS_VERSION_MAJOR_FMDB_common 2
#define COCOAPODS_VERSION_MINOR_FMDB_common 5
#define COCOAPODS_VERSION_PATCH_FMDB_common 0

// FMDB/standard
#define COCOAPODS_POD_AVAILABLE_FMDB_standard
#define COCOAPODS_VERSION_MAJOR_FMDB_standard 2
#define COCOAPODS_VERSION_MINOR_FMDB_standard 5
#define COCOAPODS_VERSION_PATCH_FMDB_standard 0

// GCPlaceholderTextView
#define COCOAPODS_POD_AVAILABLE_GCPlaceholderTextView
#define COCOAPODS_VERSION_MAJOR_GCPlaceholderTextView 1
#define COCOAPODS_VERSION_MINOR_GCPlaceholderTextView 0
#define COCOAPODS_VERSION_PATCH_GCPlaceholderTextView 1

// JSONModel
#define COCOAPODS_POD_AVAILABLE_JSONModel
#define COCOAPODS_VERSION_MAJOR_JSONModel 1
#define COCOAPODS_VERSION_MINOR_JSONModel 1
#define COCOAPODS_VERSION_PATCH_JSONModel 0

// MBProgressHUD
#define COCOAPODS_POD_AVAILABLE_MBProgressHUD
#define COCOAPODS_VERSION_MAJOR_MBProgressHUD 0
#define COCOAPODS_VERSION_MINOR_MBProgressHUD 9
#define COCOAPODS_VERSION_PATCH_MBProgressHUD 1

// MKNetworkKit
#define COCOAPODS_POD_AVAILABLE_MKNetworkKit
#define COCOAPODS_VERSION_MAJOR_MKNetworkKit 0
#define COCOAPODS_VERSION_MINOR_MKNetworkKit 87
#define COCOAPODS_VERSION_PATCH_MKNetworkKit 0

// MLLabel
#define COCOAPODS_POD_AVAILABLE_MLLabel
#define COCOAPODS_VERSION_MAJOR_MLLabel 1
#define COCOAPODS_VERSION_MINOR_MLLabel 1
#define COCOAPODS_VERSION_PATCH_MLLabel 0

// MZTimerLabel
#define COCOAPODS_POD_AVAILABLE_MZTimerLabel
#define COCOAPODS_VERSION_MAJOR_MZTimerLabel 0
#define COCOAPODS_VERSION_MINOR_MZTimerLabel 5
#define COCOAPODS_VERSION_PATCH_MZTimerLabel 2

// Masonry
#define COCOAPODS_POD_AVAILABLE_Masonry
#define COCOAPODS_VERSION_MAJOR_Masonry 0
#define COCOAPODS_VERSION_MINOR_Masonry 6
#define COCOAPODS_VERSION_PATCH_Masonry 2

// Pingpp/Alipay
#define COCOAPODS_POD_AVAILABLE_Pingpp_Alipay
#define COCOAPODS_VERSION_MAJOR_Pingpp_Alipay 2
#define COCOAPODS_VERSION_MINOR_Pingpp_Alipay 0
#define COCOAPODS_VERSION_PATCH_Pingpp_Alipay 6

// Pingpp/Core
#define COCOAPODS_POD_AVAILABLE_Pingpp_Core
#define COCOAPODS_VERSION_MAJOR_Pingpp_Core 2
#define COCOAPODS_VERSION_MINOR_Pingpp_Core 0
#define COCOAPODS_VERSION_PATCH_Pingpp_Core 6

// Pingpp/Wx
#define COCOAPODS_POD_AVAILABLE_Pingpp_Wx
#define COCOAPODS_VERSION_MAJOR_Pingpp_Wx 2
#define COCOAPODS_VERSION_MINOR_Pingpp_Wx 0
#define COCOAPODS_VERSION_PATCH_Pingpp_Wx 6

// Qiniu
#define COCOAPODS_POD_AVAILABLE_Qiniu
#define COCOAPODS_VERSION_MAJOR_Qiniu 7
#define COCOAPODS_VERSION_MINOR_Qiniu 0
#define COCOAPODS_VERSION_PATCH_Qiniu 11

// Reachability
#define COCOAPODS_POD_AVAILABLE_Reachability
#define COCOAPODS_VERSION_MAJOR_Reachability 3
#define COCOAPODS_VERSION_MINOR_Reachability 1
#define COCOAPODS_VERSION_PATCH_Reachability 1

// SDWebImage
#define COCOAPODS_POD_AVAILABLE_SDWebImage
#define COCOAPODS_VERSION_MAJOR_SDWebImage 3
#define COCOAPODS_VERSION_MINOR_SDWebImage 7
#define COCOAPODS_VERSION_PATCH_SDWebImage 2

// SDWebImage/Core
#define COCOAPODS_POD_AVAILABLE_SDWebImage_Core
#define COCOAPODS_VERSION_MAJOR_SDWebImage_Core 3
#define COCOAPODS_VERSION_MINOR_SDWebImage_Core 7
#define COCOAPODS_VERSION_PATCH_SDWebImage_Core 2

// UITableView+FDTemplateLayoutCell
#define COCOAPODS_POD_AVAILABLE_UITableView_FDTemplateLayoutCell
#define COCOAPODS_VERSION_MAJOR_UITableView_FDTemplateLayoutCell 1
#define COCOAPODS_VERSION_MINOR_UITableView_FDTemplateLayoutCell 3
#define COCOAPODS_VERSION_PATCH_UITableView_FDTemplateLayoutCell 0

// UITextField+Shake
#define COCOAPODS_POD_AVAILABLE_UITextField_Shake
#define COCOAPODS_VERSION_MAJOR_UITextField_Shake 1
#define COCOAPODS_VERSION_MINOR_UITextField_Shake 0
#define COCOAPODS_VERSION_PATCH_UITextField_Shake 0

// UMengAnalytics
#define COCOAPODS_POD_AVAILABLE_UMengAnalytics
#define COCOAPODS_VERSION_MAJOR_UMengAnalytics 3
#define COCOAPODS_VERSION_MINOR_UMengAnalytics 5
#define COCOAPODS_VERSION_PATCH_UMengAnalytics 8

// UMengSocial
#define COCOAPODS_POD_AVAILABLE_UMengSocial
#define COCOAPODS_VERSION_MAJOR_UMengSocial 4
#define COCOAPODS_VERSION_MINOR_UMengSocial 2
#define COCOAPODS_VERSION_PATCH_UMengSocial 3

